# pyproject.toml
[build-system]
requires = ["setuptools>=39", "setuptools_scm[toml]>=3.4"]
build-backend = 'setuptools.build_meta'
[tool.setuptools_scm]
write_to = "flask_multipass_ldap_mlz/version.py" 
